/*
 * pathfinder-endpoint
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-beta2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ClimateCamp.GHG.Calculations.Pathfinder
{ 
        /// <summary>
        /// Gets or Sets ProductOrSectorSpecificRuleOperator
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ProductOrSectorSpecificRuleOperator
        {
            /// <summary>
            /// Enum PEFEnum for PEF
            /// </summary>
            [EnumMember(Value = "PEF")]
            PEFEnum = 0,
            /// <summary>
            /// Enum EPDInternationalEnum for EPD International
            /// </summary>
            [EnumMember(Value = "EPD International")]
            EPDInternationalEnum = 1,
            /// <summary>
            /// Enum OtherEnum for Other
            /// </summary>
            [EnumMember(Value = "Other")]
            OtherEnum = 2        }
}
