/*
 * pathfinder-endpoint
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-beta2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ClimateCamp.GHG.Calculations.Pathfinder
{ 
        /// <summary>
        /// List of UN regions and subregions
        /// </summary>
        /// <value>List of UN regions and subregions</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum UNRegionOrSubregion
        {
            /// <summary>
            /// Enum AfricaEnum for Africa
            /// </summary>
            [EnumMember(Value = "Africa")]
            AfricaEnum = 0,
            /// <summary>
            /// Enum AmericasEnum for Americas
            /// </summary>
            [EnumMember(Value = "Americas")]
            AmericasEnum = 1,
            /// <summary>
            /// Enum AsiaEnum for Asia
            /// </summary>
            [EnumMember(Value = "Asia")]
            AsiaEnum = 2,
            /// <summary>
            /// Enum EuropeEnum for Europe
            /// </summary>
            [EnumMember(Value = "Europe")]
            EuropeEnum = 3,
            /// <summary>
            /// Enum OceaniaEnum for Oceania
            /// </summary>
            [EnumMember(Value = "Oceania")]
            OceaniaEnum = 4,
            /// <summary>
            /// Enum AustraliaAndNewZealandEnum for Australia and New Zealand
            /// </summary>
            [EnumMember(Value = "Australia and New Zealand")]
            AustraliaAndNewZealandEnum = 5,
            /// <summary>
            /// Enum CentralAsiaEnum for Central Asia
            /// </summary>
            [EnumMember(Value = "Central Asia")]
            CentralAsiaEnum = 6,
            /// <summary>
            /// Enum EasternAsiaEnum for Eastern Asia
            /// </summary>
            [EnumMember(Value = "Eastern Asia")]
            EasternAsiaEnum = 7,
            /// <summary>
            /// Enum EasternEuropeEnum for Eastern Europe
            /// </summary>
            [EnumMember(Value = "Eastern Europe")]
            EasternEuropeEnum = 8,
            /// <summary>
            /// Enum LatinAmericaAndTheCaribbeanEnum for Latin America and the Caribbean
            /// </summary>
            [EnumMember(Value = "Latin America and the Caribbean")]
            LatinAmericaAndTheCaribbeanEnum = 9,
            /// <summary>
            /// Enum MelanesiaEnum for Melanesia
            /// </summary>
            [EnumMember(Value = "Melanesia")]
            MelanesiaEnum = 10,
            /// <summary>
            /// Enum MicronesiaEnum for Micronesia
            /// </summary>
            [EnumMember(Value = "Micronesia")]
            MicronesiaEnum = 11,
            /// <summary>
            /// Enum NorthernAfricaEnum for Northern Africa
            /// </summary>
            [EnumMember(Value = "Northern Africa")]
            NorthernAfricaEnum = 12,
            /// <summary>
            /// Enum NorthernAmericaEnum for Northern America
            /// </summary>
            [EnumMember(Value = "Northern America")]
            NorthernAmericaEnum = 13,
            /// <summary>
            /// Enum NorthernEuropeEnum for Northern Europe
            /// </summary>
            [EnumMember(Value = "Northern Europe")]
            NorthernEuropeEnum = 14,
            /// <summary>
            /// Enum PolynesiaEnum for Polynesia
            /// </summary>
            [EnumMember(Value = "Polynesia")]
            PolynesiaEnum = 15,
            /// <summary>
            /// Enum SouthEasternAsiaEnum for South-eastern Asia
            /// </summary>
            [EnumMember(Value = "South-eastern Asia")]
            SouthEasternAsiaEnum = 16,
            /// <summary>
            /// Enum SouthernAsiaEnum for Southern Asia
            /// </summary>
            [EnumMember(Value = "Southern Asia")]
            SouthernAsiaEnum = 17,
            /// <summary>
            /// Enum SouthernEuropeEnum for Southern Europe
            /// </summary>
            [EnumMember(Value = "Southern Europe")]
            SouthernEuropeEnum = 18,
            /// <summary>
            /// Enum SubSaharanAfricaEnum for Sub-Saharan Africa
            /// </summary>
            [EnumMember(Value = "Sub-Saharan Africa")]
            SubSaharanAfricaEnum = 19,
            /// <summary>
            /// Enum WesternAsiaEnum for Western Asia
            /// </summary>
            [EnumMember(Value = "Western Asia")]
            WesternAsiaEnum = 20,
            /// <summary>
            /// Enum WesternEuropeEnum for Western Europe
            /// </summary>
            [EnumMember(Value = "Western Europe")]
            WesternEuropeEnum = 21        }
}
