using ClimateCamp.Lookup;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace ClimateCamp.EntityFrameworkCore.Seed.Host.Lookup
{
    public class DefaultCountryCreator
    {
        private readonly CommonDbContext _context;

        public DefaultCountryCreator(CommonDbContext context)
        {
            _context = context;
        }

        public void Create()
        {
            CreateCountries();
        }

        private void CreateCountries()
        {
            foreach (var country in GetInitialCountries())
            {
                AddUnitIfNotExists(country);
            }
        }

        private void AddUnitIfNotExists(Country country)
        {
            if (_context.Countries.IgnoreQueryFilters().Any(t => t.Name == country.Name))
            {
                return;
            }

            _context.Countries.Add(country);
            _context.SaveChanges();
        }

        private List<Country> GetInitialCountries()
        {
            return new List<Country>
            {
                new Country("Afghanistan","AF","AFG"),
                new Country("Aland Islands","AX","ALA"),
                new Country("Albania","AL","ALB"),
                new Country("Algeria","DZ","DZA"),
                new Country("American Samoa","AS","ASM"),
                new Country("Andorra","AD","AND"),
                new Country("Angola","AO","AGO"),
                new Country("Anguilla","AI","AIA"),
                new Country("Antarctica","AQ","ATA"),
                new Country("Antigua and Barbuda","AG","ATG"),
                new Country("Argentina","AR","ARG"),
                new Country("Armenia","AM","ARM"),
                new Country("Aruba","AW","ABW"),
                new Country("Australia","AU","AUS"),
                new Country("Austria","AT","AUT"),
                new Country("Azerbaijan","AZ","AZE"),
                new Country("Bahamas","BS","BHS"),
                new Country("Bahrain","BH","BHR"),
                new Country("Bangladesh","BD","BGD"),
                new Country("Barbados","BB","BRB"),
                new Country("Belarus","BY","BLR"),
                new Country("Belgium","BE","BEL"),
                new Country("Belize","BZ","BLZ"),
                new Country("Benin","BJ","BEN"),
                new Country("Bermuda","BM","BMU"),
                new Country("Bhutan","BT","BTN"),
                new Country("Bolivia","BO","BOL"),
                new Country("Bonaire, Sint Eustatius and Saba","BQ","BES"),
                new Country("Bosnia and Herzegovina","BA","BIH"),
                new Country("Botswana","BW","BWA"),
                new Country("Bouvet Island","BV","BVT"),
                new Country("Brazil","BR","BRA"),
                new Country("British Indian Ocean Territory","IO","IOT"),
                new Country("Brunei","BN","BRN"),
                new Country("Bulgaria","BG","BGR"),
                new Country("Burkina Faso","BF","BFA"),
                new Country("Burundi","BI","BDI"),
                new Country("Cambodia","KH","KHM"),
                new Country("Cameroon","CM","CMR"),
                new Country("Canada","CA","CAN"),
                new Country("Cape Verde","CV","CPV"),
                new Country("Cayman Islands","KY","CYM"),
                new Country("Central African Republic","CF","CAF"),
                new Country("Chad","TD","TCD"),
                new Country("Chile","CL","CHL"),
                new Country("China","CN","CHN"),
                new Country("Christmas Island","CX","CXR"),
                new Country("Cocos (Keeling) Islands","CC","CCK"),
                new Country("Colombia","CO","COL"),
                new Country("Comoros","KM","COM"),
                new Country("Congo","CG","COG"),
                new Country("Cook Islands","CK","COK"),
                new Country("Costa Rica","CR","CRI"),
                new Country("Ivory Coast","CI","CIV"),
                new Country("Croatia","HR","HRV"),
                new Country("Cuba","CU","CUB"),
                new Country("Curacao","CW","CUW"),
                new Country("Cyprus","CY","CYP"),
                new Country("Czech Republic","CZ","CZE"),
                new Country("Democratic Republic of the Congo","CD","COD"),
                new Country("Denmark","DK","DNK"),
                new Country("Djibouti","DJ","DJI"),
                new Country("Dominica","DM","DMA"),
                new Country("Dominican Republic","DO","DOM"),
                new Country("Ecuador","EC","ECU"),
                new Country("Egypt","EG","EGY"),
                new Country("El Salvador","SV","SLV"),
                new Country("Equatorial Guinea","GQ","GNQ"),
                new Country("Eritrea","ER","ERI"),
                new Country("Estonia","EE","EST"),
                new Country("Ethiopia","ET","ETH"),
                new Country("Falkland Islands (Malvinas)","FK","FLK"),
                new Country("Faroe Islands","FO","FRO"),
                new Country("Fiji","FJ","FJI"),
                new Country("Finland","FI","FIN"),
                new Country("France","FR","FRA"),
                new Country("French Guiana","GF","GUF"),
                new Country("French Polynesia","PF","PYF"),
                new Country("French Southern Territories","TF","ATF"),
                new Country("Gabon","GA","GAB"),
                new Country("Gambia","GM","GMB"),
                new Country("Georgia","GE","GEO"),
                new Country("Germany","DE","DEU"),
                new Country("Ghana","GH","GHA"),
                new Country("Gibraltar","GI","GIB"),
                new Country("Greece","GR","GRC"),
                new Country("Greenland","GL","GRL"),
                new Country("Grenada","GD","GRD"),
                new Country("Guadaloupe","GP","GLP"),
                new Country("Guam","GU","GUM"),
                new Country("Guatemala","GT","GTM"),
                new Country("Guernsey","GG","GGY"),
                new Country("Guinea","GN","GIN"),
                new Country("Guinea-Bissau","GW","GNB"),
                new Country("Guyana","GY","GUY"),
                new Country("Haiti","HT","HTI"),
                new Country("Heard Island and McDonald Islands","HM","HMD"),
                new Country("Honduras","HN","HND"),
                new Country("Hong Kong","HK","HKG"),
                new Country("Hungary","HU","HUN"),
                new Country("Iceland","IS","ISL"),
                new Country("India","IN","IND"),
                new Country("Indonesia","ID","IDN"),
                new Country("Iran","IR","IRN"),
                new Country("Iraq","IQ","IRQ"),
                new Country("Ireland","IE","IRL"),
                new Country("Isle of Man","IM","IMN"),
                new Country("Israel","IL","ISR"),
                new Country("Italy","IT","ITA"),
                new Country("Jamaica","JM","JAM"),
                new Country("Japan","JP","JPN"),
                new Country("Jersey","JE","JEY"),
                new Country("Jordan","JO","JOR"),
                new Country("Kazakhstan","KZ","KAZ"),
                new Country("Kenya","KE","KEN"),
                new Country("Kiribati","KI","KIR"),
                new Country("Kosovo","XK","---"),
                new Country("Kuwait","KW","KWT"),
                new Country("Kyrgyzstan","KG","KGZ"),
                new Country("Laos","LA","LAO"),
                new Country("Latvia","LV","LVA"),
                new Country("Lebanon","LB","LBN"),
                new Country("Lesotho","LS","LSO"),
                new Country("Liberia","LR","LBR"),
                new Country("Libya","LY","LBY"),
                new Country("Liechtenstein","LI","LIE"),
                new Country("Lithuania","LT","LTU"),
                new Country("Luxembourg","LU","LUX"),
                new Country("Macao","MO","MAC"),
                new Country("Macedonia","MK","MKD"),
                new Country("Madagascar","MG","MDG"),
                new Country("Malawi","MW","MWI"),
                new Country("Malaysia","MY","MYS"),
                new Country("Maldives","MV","MDV"),
                new Country("Mali","ML","MLI"),
                new Country("Malta","MT","MLT"),
                new Country("Marshall Islands","MH","MHL"),
                new Country("Martinique","MQ","MTQ"),
                new Country("Mauritania","MR","MRT"),
                new Country("Mauritius","MU","MUS"),
                new Country("Mayotte","YT","MYT"),
                new Country("Mexico","MX","MEX"),
                new Country("Micronesia","FM","FSM"),
                new Country("Moldava","MD","MDA"),
                new Country("Monaco","MC","MCO"),
                new Country("Mongolia","MN","MNG"),
                new Country("Montenegro","ME","MNE"),
                new Country("Montserrat","MS","MSR"),
                new Country("Morocco","MA","MAR"),
                new Country("Mozambique","MZ","MOZ"),
                new Country("Myanmar (Burma)","MM","MMR"),
                new Country("Namibia","NA","NAM"),
                new Country("Nauru","NR","NRU"),
                new Country("Nepal","NP","NPL"),
                new Country("Netherlands","NL","NLD"),
                new Country("New Caledonia","NC","NCL"),
                new Country("New Zealand","NZ","NZL"),
                new Country("Nicaragua","NI","NIC"),
                new Country("Niger","NE","NER"),
                new Country("Nigeria","NG","NGA"),
                new Country("Niue","NU","NIU"),
                new Country("Norfolk Island","NF","NFK"),
                new Country("North Korea","KP","PRK"),
                new Country("Northern Mariana Islands","MP","MNP"),
                new Country("Norway","NO","NOR"),
                new Country("Oman","OM","OMN"),
                new Country("Pakistan","PK","PAK"),
                new Country("Palau","PW","PLW"),
                new Country("Palestine","PS","PSE"),
                new Country("Panama","PA","PAN"),
                new Country("Papua New Guinea","PG","PNG"),
                new Country("Paraguay","PY","PRY"),
                new Country("Peru","PE","PER"),
                new Country("Phillipines","PH","PHL"),
                new Country("Pitcairn","PN","PCN"),
                new Country("Poland","PL","POL"),
                new Country("Portugal","PT","PRT"),
                new Country("Puerto Rico","PR","PRI"),
                new Country("Qatar","QA","QAT"),
                new Country("Reunion","RE","REU"),
                new Country("Romania","RO","ROU"),
                new Country("Russia","RU","RUS"),
                new Country("Rwanda","RW","RWA"),
                new Country("Saint Barthelemy","BL","BLM"),
                new Country("Saint Helena","SH","SHN"),
                new Country("Saint Kitts and Nevis","KN","KNA"),
                new Country("Saint Lucia","LC","LCA"),
                new Country("Saint Martin","MF","MAF"),
                new Country("Saint Pierre and Miquelon","PM","SPM"),
                new Country("Saint Vincent and the Grenadines","VC","VCT"),
                new Country("Samoa","WS","WSM"),
                new Country("San Marino","SM","SMR"),
                new Country("Sao Tome and Principe","ST","STP"),
                new Country("Saudi Arabia","SA","SAU"),
                new Country("Senegal","SN","SEN"),
                new Country("Serbia","RS","SRB"),
                new Country("Seychelles","SC","SYC"),
                new Country("Sierra Leone","SL","SLE"),
                new Country("Singapore","SG","SGP"),
                new Country("Sint Maarten","SX","SXM"),
                new Country("Slovakia","SK","SVK"),
                new Country("Slovenia","SI","SVN"),
                new Country("Solomon Islands","SB","SLB"),
                new Country("Somalia","SO","SOM"),
                new Country("South Africa","ZA","ZAF"),
                new Country("South Georgia and the South Sandwich Islands","GS","SGS"),
                new Country("South Korea","KR","KOR"),
                new Country("South Sudan","SS","SSD"),
                new Country("Spain","ES","ESP"),
                new Country("Sri Lanka","LK","LKA"),
                new Country("Sudan","SD","SDN"),
                new Country("Suriname","SR","SUR"),
                new Country("Svalbard and Jan Mayen","SJ","SJM"),
                new Country("Swaziland","SZ","SWZ"),
                new Country("Sweden","SE","SWE"),
                new Country("Switzerland","CH","CHE"),
                new Country("Syria","SY","SYR"),
                new Country("Taiwan","TW","TWN"),
                new Country("Tajikistan","TJ","TJK"),
                new Country("Tanzania","TZ","TZA"),
                new Country("Thailand","TH","THA"),
                new Country("Timor-Leste (East Timor)","TL","TLS"),
                new Country("Togo","TG","TGO"),
                new Country("Tokelau","TK","TKL"),
                new Country("Tonga","TO","TON"),
                new Country("Trinidad and Tobago","TT","TTO"),
                new Country("Tunisia","TN","TUN"),
                new Country("Turkey","TR","TUR"),
                new Country("Turkmenistan","TM","TKM"),
                new Country("Turks and Caicos Islands","TC","TCA"),
                new Country("Tuvalu","TV","TUV"),
                new Country("Uganda","UG","UGA"),
                new Country("Ukraine","UA","UKR"),
                new Country("United Arab Emirates","AE","ARE"),
                new Country("United Kingdom","GB","GBR"),
                new Country("United States","US","USA"),
                new Country("United States Minor Outlying Islands","UM","UMI"),
                new Country("Uruguay","UY","URY"),
                new Country("Uzbekistan","UZ","UZB"),
                new Country("Vanuatu","VU","VUT"),
                new Country("Vatican City","VA","VAT"),
                new Country("Venezuela","VE","VEN"),
                new Country("Vietnam","VN","VNM"),
                new Country("Virgin Islands, British","VG","VGB"),
                new Country("Virgin Islands, US","VI","VIR"),
                new Country("Wallis and Futuna","WF","WLF"),
                new Country("Western Sahara","EH","ESH"),
                new Country("Yemen","YE","YEM"),
                new Country("Zambia","ZM","ZMB"),
                new Country("Zimbabwe","ZW","ZWE"),
            };
        }

    }
}
